pr trigger added

diff --git a/.github/workflows/smokesuite.yml b/.github/workflows/smokesuite.yml
--- a/.github/workflows/smokesuite.yml
+++ b/.github/workflows/smokesuite.yml
@@ -1,9 +1,7 @@
 name: Smoke Suite
 
 on:
-  pull_request:
-    types: [opened, synchronize, reopened]
-    branches: [main, develop]
+  
   push:
     branches: [jay]
   workflow_dispatch:
@@ -20,8 +18,10 @@ concurrency:
 
 jobs:
   regression:
-    name: Run Automation Regression
+    name: Run Automation Regression + Deploy Github Pages Report
     runs-on: ubuntu-latest
+    environment:
+      name: github-pages
 
     steps:
       - name: Checkout code
@@ -59,65 +59,16 @@ jobs:
         with:
           name: allure-results
           path: allure-results/
-          
-     # -------------------------
-      # PR TEST SUMMARY
-      # -------------------------
-      - name: Publish test summary to PR
-        if: always() && github.event_name == 'pull_request'
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const fs = require('fs');
 
-            if (!fs.existsSync('playwright-results.json')) {
-              console.log('No Playwright JSON found');
-              return;
-            }
-
-            const results = JSON.parse(
-              fs.readFileSync('playwright-results.json', 'utf8')
-            );
-
-            let failed = 0;
-            let passed = 0;
-
-            for (const suite of results.suites ?? []) {
-              for (const spec of suite.specs ?? []) {
-                for (const test of spec.tests ?? []) {
-                  if (test.outcome === 'unexpected') failed++;
-                  if (test.outcome === 'expected') passed++;
-                }
-              }
-            }
-
-            const body = `
-            🧪 **Playwright Test Summary**
-
-            ✅ Passed: **${passed}**  
-            ❌ Failed: **${failed}**
-
-            📄 **HTML Report:**  
-            👉 https://jay-ut.github.io/utis-playwright-framework/
-            `;
-
-            await github.rest.issues.createComment({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-              body
-            });
-     
-
-  deploy:
-    name: Deploy to GitHub Pages
-    needs: regression
-    runs-on: ubuntu-latest
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
-
-    steps:
-      - name: Deploy
+      - name: Deploy Playwright report to GitHub Pages
+        if: always()
         id: deployment
         uses: actions/deploy-pages@v4
+        continue-on-error: true
+          
+      - name: Fail if test cases failed
+        if: steps.run_tests.outcome == 'failure'
+        run: |
+                echo "Tests failed ❌"
+                exit 1  
+     
